### ISSUE TITLE
애플 워치 지원 추가

### ISSUE THREAD

**Issue by niceb5y** [niceb5y/DRSTm#5]
WatchOS2 App으로 구현

**Comment by niceb5y** [comment]
03faf716e6b46434370408ab50d99b519282931d 애플워치 타겟 추가

**Comment by niceb5y** [comment]
일단 아이클라우드 기반으로만 작동하게 만들까...

**Comment by LEESEHA** [comment]
기다리고있어요 애플워치 어플!!

**Comment by niceb5y** [comment]
b3d9ad24d6079ed9c1b8d0b3e0c0f691e6c5d530 아이콘 추가
d6f7832e887aeeb28982f3d7fd1d6748a0febd4e 편집기능 빼고 모두 구현

**Comment by niceb5y** [comment]
f3f649ab1f969bedbeeaece1a672e0de21a40ca2 편집기능 구현

**Comment by niceb5y** [comment]
#14 일단 완성
