### ISSUE TITLE
다중 계정 저장 시, 다른 계정까지 영향을 끼치는 문제

### ISSUE THREAD

**Issue by niceb5y** [niceb5y/DRSTm#8]
상황은 설정의 옵션 3개가 다 켜져있는 상태(하지만 아이폰만 사용중)

기기1 52/69
기기2 41/51

상태에서 기기 1을 플레이 한 후 앱을 켜서 기기 1만 스태미너를 2로 입력하고 바로 저장 -> 기기2 13/51로 변화

**Comment by niceb5y** [comment]
구조상 프레임워크 보다는 뷰 컨트롤러 문제가 아닐지?

**Comment by MIJELU** [comment]
성공적인 앱 개발을 응원합니다

**Comment by niceb5y** [comment]
너 왜 시시냐

**Comment by niceb5y** [comment]
너 왜 시비냐

**Comment by niceb5y** [comment]
원인도 모르겠고 재현도 힘드므로 저장 구조 변경하면서 처리하는 것으로.
